openapi: 3.1.0

info:
  title: Payment Notice Microservice
  version: 13.2.0
  description: Payment Notice Microservice for Multi-channel Integration Layer of SW Client Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: Development Test
    url: https://mil-d-apim.azure-api.net/mil-payment-notice
    x-internal: true
  - description: User Acceptance Test
    url: https://mil-u-apim.azure-api.net/mil-payment-notice
    x-internal: true

security:
  - bearerAuth: [ ]

paths:
  /paymentNotices:
    # ------------------------------------------------------
    # Retrieves debt position
    # ------------------------------------------------------
    get:
      operationId: getDebtPosition
      summary: Retrieves debt position
      description: Retrieves the debt position using the tax code token contained in the access token
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/AcquirerId'
        - $ref: '#/components/parameters/Channel'
        - $ref: '#/components/parameters/MerchantId'
        - $ref: '#/components/parameters/TerminalId'
      responses:
        "200":
          $ref: '#/components/responses/DebtPosition'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /paymentNotices/{qrCode}:
    parameters:
      - $ref: '#/components/parameters/RequestId'
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/AcquirerId'
      - $ref: '#/components/parameters/Channel'
      - $ref: '#/components/parameters/MerchantId'
      - $ref: '#/components/parameters/TerminalId'
      - name: qrCode
        description: Base64Url of the string encoded by the QR-code. This is due to a bug of Azure routing system which decodes %2F before routing the request.
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/QrCodeBase64UrlEnc'

    # ------------------------------------------------------
    # Verifies a payment notice by QR-code
    # ------------------------------------------------------
    get:
      operationId: verifyByQrCode
      summary: Verifies a payment notice by QR-code
      responses:
        "200":
          $ref: '#/components/responses/VerifyProcessed'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Activates the payment of a notice by QR-code
    # ------------------------------------------------------
    patch:
      operationId: activateByQrCode
      summary: Activates the payment of a notice by QR-code
      requestBody:
        $ref: '#/components/requestBodies/Activate'
      responses:
        "200":
          $ref: '#/components/responses/ActivateProcessed'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /paymentNotices/{paTaxCode}/{noticeNumber}:
    parameters:
      - $ref: '#/components/parameters/RequestId'
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/AcquirerId'
      - $ref: '#/components/parameters/Channel'
      - $ref: '#/components/parameters/MerchantId'
      - $ref: '#/components/parameters/TerminalId'
      - name: paTaxCode
        description: Tax code of the creditor company
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/PaTaxCode'
      - name: noticeNumber
        description: Notice number
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/NoticeNumber'

    # ------------------------------------------------------
    # Verifies a payment notice by PA tax code and notice
    # number
    # ------------------------------------------------------
    get:
      operationId: verifyByTaxCodeAndNoticeNumber
      summary: Verifies a payment notice by PA tax code and notice number
      responses:
        "200":
          $ref: '#/components/responses/VerifyProcessed'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Activates the payment of a notice by PA tax code and
    # notice number
    # ------------------------------------------------------
    patch:
      operationId: activateByTaxCodeAndNoticeNumber
      summary: Activates the payment of a notice by PA tax code and notice number
      requestBody:
        $ref: '#/components/requestBodies/Activate'
      responses:
        "200":
          $ref: '#/components/responses/ActivateProcessed'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /payments:
    parameters:
      - $ref: '#/components/parameters/RequestId'
      - $ref: '#/components/parameters/Version'
      - $ref: '#/components/parameters/AcquirerId'
      - $ref: '#/components/parameters/Channel'
      - $ref: '#/components/parameters/MerchantId'
      - $ref: '#/components/parameters/TerminalId'

    # ------------------------------------------------------
    # Pre-closes or aborts the payment of a set of notices
    # ------------------------------------------------------
    post:
      operationId: preCloseOrAbort
      summary: Pre-closes or aborts the payment of a set of notices
      requestBody:
        $ref: '#/components/requestBodies/PreCloseOrAbort'
      responses:
        "201":
          $ref: '#/components/responses/PreCloseOrAbortProcessed'
        "202":
          description: Only for abort operation.
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "409":
          description: Transaction ID already exists
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Gets last 30 transactions executed by the client in
    # the last 30 days
    # ------------------------------------------------------
    get:
      operationId: getLastTransactions
      summary: Gets last 30 transactions executed by the client in the last 30 days
      responses:
        "200":
          $ref: '#/components/responses/Transactions'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error
          
  /payments/{transactionId}:
    parameters:
      - name: transactionId
        description: Transaction ID
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/TransactionId'

    # ------------------------------------------------------
    # Comunicates the outcome of the e-money transaction
    # executed to pay a set of notices
    # ------------------------------------------------------
    patch:
      operationId: close
      summary: Comunicates the outcome of the e-money transaction executed to pay a set of notices
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/AcquirerId'
        - $ref: '#/components/parameters/Channel'
        - $ref: '#/components/parameters/MerchantId'
        - $ref: '#/components/parameters/TerminalId'
      requestBody:
        $ref: '#/components/requestBodies/Close'
      responses:
        "201":
          $ref: '#/components/responses/CloseProcessed'
        "202":
          description: Only for operation with KO outcome
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Retrieves the status of the payment of a set of
    # payment notices
    # ------------------------------------------------------
    get:
      operationId: getPaymentStatus
      summary: Retrieves the status of the payment of a set of payment notices
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/AcquirerId'
        - $ref: '#/components/parameters/Channel'
        - $ref: '#/components/parameters/MerchantId'
        - $ref: '#/components/parameters/TerminalId'
      responses:
        "200":
          $ref: '#/components/responses/PaymentStatus'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment status not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Receives from the Nodo the result of the payment of a
    # set of payment notices
    # ------------------------------------------------------
    post:
      operationId: receivePaymentStatus
      summary: Receives from the Nodo the result of the payment of a set of payment notices. This API is invoked by the Nodo for sendPaymentResult.
      requestBody:
        $ref: '#/components/requestBodies/PaymentStatusByNodo'
      responses:
        "200":
          $ref: '#/components/responses/PaymentStatusReceived'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          $ref: '#/components/responses/TransactionNotFound'
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Schemas
  # ========================================================
  schemas:
    # ------------------------------------------------------
    # Basic types
    # ------------------------------------------------------
    AccessControlAllowOrigin:
      description: Indicates whether the response can be shared with requesting code from the given origin
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048

    BrokerId:
      description: ID of pagoPA broker
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,35}$"
      minLength: 1
      maxLength: 35
      example: "97735020584"

    Channel:
      description: Channel used to pay
      enum:
        - ATM
        - POS
      type: string
      example: "ATM"

    ChannelId:
      description: ID of pagoPA channel
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,35}$"
      minLength: 1
      maxLength: 35
      example: "97735020584_03"

    CreationTimestamp:
      description: Moment of creation of the transaction
      type: string
      format: date-time
      pattern: "^\\d{4}\\-\\d{2}\\-\\d{2}T\\d{2}:\\d{2}:\\d{2}(Z|(\\+|\\-)\\d{2}:\\d{2})$"
      minLength: 20
      maxLength: 25
      examples:
        - "2024-03-06T13:15:54Z"
        - "2024-03-06T14:15:54+01:00"

    CreditorReferenceId:
      description: IUV of the notice
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,35}$"
      minLength: 1
      maxLength: 35
      example: "48394875506035295"

    DueDate:
      description: Expiration date of the notice
      type: string
      format: date
      maxLength: 10
      example: "2022-11-30"

    Description:
      description: Notice description
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "Health ticket for chest x-ray"

    ErrorCode:
      description: Error code
      type: string
      pattern: "^[A-F0-9]{9}$"
      minLength: 9
      maxLength: 9
      example: "001000005"

    ErrorDescription:
      description: Error description
      type: string
      pattern: "^[ -~]{1,256}$"
      minLength: 1
      maxLength: 256
      example: "Unexpected error from server"

    EuroCents:
      description: Amount in euro cents
      type: integer
      format: int64
      minimum: 1
      maximum: 99999999999
      example: 12345

    Iban:
      description: IBAN of the payee
      type: string
      pattern: "^IT[0-9]{2}[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$"
      minLength: 27
      maxLength: 27
      example: "IT12A1234512345123456789012"
    
    IdempotencyKey:
      description: Idempotency key for activate request
      type: string
      pattern: "^[0-9]{11}_[a-zA-Z0-9]{10}$"
      minLength: 22
      maxLength: 22
      example: "47583764545_Ahf479elk0"

    IdBundle:
      description: ID of fees bundle
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,70}$"
      minLength: 1
      maxLength: 70
      example: "457"
    
    IdCiBundle:
      description: ID of the payee which pays part of the fees
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,70}$"
      minLength: 1
      maxLength: 70
      example: "06534340721"

    LastUpdateTimestamp:
      description: Moment of last update of the transaction
      type: string
      format: date-time
      pattern: "^\\d{4}\\-\\d{2}\\-\\d{2}T\\d{2}:\\d{2}:\\d{2}(Z|(\\+|\\-)\\d{2}:\\d{2})$"
      minLength: 20
      maxLength: 25
      examples:
        - "2024-03-06T13:15:54Z"
        - "2024-03-06T14:15:54+01:00"

    MetadataKey:
      description: Key of metadata
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "INT_REF"
      
    MetadataValue:
      description: Value of metadata
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "123.456.00"

    NoticeNumber:
      description: Notice number
      type: string
      pattern: "^[0-9]{18}$"
      minLength: 18
      maxLength: 18
      example: "485564829563528563"

    Office:
      description: Name of the payee office
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "Ufficio di Roma"

    Outcome:
      description: Outcome returned to verify and activate operations when something went wrong (this will be removed)
      type: string
      enum:
        - NOTICE_GLITCH               # Spiacenti, c'è un problema tecnico con questo avviso.
        - WRONG_NOTICE_DATA           # Spiacenti, i dati dell’avviso non sono corretti.
        - CREDITOR_PROBLEMS           # Spiacenti, l’Ente Creditore sta avendo problemi nella risposta.
        - PAYMENT_ALREADY_IN_PROGRESS # Il pagamento è già in corso, riprova fra qualche minuto.
        - EXPIRED_NOTICE              # Spiacenti, l’avviso è scaduto e non è più possibile pagarlo.
        - REVOKED_NOTICE              # Spiacenti, l’Ente Creditore ha revocato questo avviso.
        - NOTICE_ALREADY_PAID         # Questo avviso è stato già pagato!
        - UNKNOWN_NOTICE              # Avviso sconosciuto.
        - UNEXPECTED_ERROR            # Spiacenti, si è verificato un errore imprevisto.
      example: "NOTICE_GLITCH"

    PageNumber:
      description: Number of the page
      type: integer
      format: int32
      minimum: 0
      maximum: 2147483647
      example: 1

    PageSize:
      description: Size of the page
      type: integer
      format: int32
      minimum: 1
      maximum: 128
      example: 20

    PayeeCode:
      description: Fiscal code of the subject that receives the payment (the payee)
      type: string
      pattern: "^\\d{11}$"
      minLength: 11
      maxLength: 11
      example: "06534340721"

    PayeeName:
      description: Name of the payee
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "ASL Roma"

    PaymentMethod:
      description: Method used to pay the notice
      type: string
      enum:
        - DOMESTIC_CARD
        - INTERNATIONAL_CARD
        - CASH
        - OTHER
      example: "DOMESTIC_CARD"

    PaymentToken:
      description: ID of the payment activation
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,35}$"
      minLength: 1
      maxLength: 35
      example: "648fhg36s95jfg7DS"

    PspId:
      description: ID of pagoPA PSP
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,35}$"
      minLength: 1
      maxLength: 35
      example: "AGID_01"

    RateLimitLimit:
      description: The number of allowed requests in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: The number of seconds to wait before allowing a follow-up request
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RemittanceInfo:
      description: Reason of the payment
      type: string
      pattern: "^[\\u0001-\\uD7FF\\uE000-\\uFFFD\\U10000-\\U10FFFF]{1,140}$"
      minLength: 1
      maxLength: 140
      example: "Health ticket for chest x-ray"

    ServiceProviderId:
      description: ID of the service provider
      type: string
      pattern: "^[ -~]{1,64}$"
      minLength: 1
      maxLength: 64
      example: "AGID_01"

    Standin:
      description: If true standin mode is in use 
      type: boolean
      example: false
    
    Status:
      description: Status of the transaction
      type: string
      enum:
        - CLOSED_OK
        - ERROR_ON_PAYMENT
        - ABORT
      example: "CLOSED_OK"

    TerminalHandlerId:
      description: Terminal handler identifier
      type: string
      pattern: "^\\d{5}$"
      minLength: 5
      maxLength: 5
      example: "45856"

    TerminalId:
      description: ID of the terminal. It must be unique per terminal handler.
      type: string
      pattern: "^\\d{8}$"
      minLength: 8
      maxLength: 8
      example: "34523860"

    TerminalUuid:
      description: UUID of a terminal
      type: string
      pattern: "^[0-9a-f]{24}$"
      minLength: 24
      maxLength: 24
      example: "c7a1b24b0583477292ebdbaa"

    TransactionId:
      description: Transaction ID
      type: string
      pattern: "^[0-9a-f]{24}$"
      minLength: 24
      maxLength: 24
      example: "4658fcb36e520a65b1be79d0"

    TransactionLocation:
      description: URL of the transaction
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
      example: "https://mil-d-apim.azure-api.net/mil-payment-notice/transactions/4658fcb36e520a65b1be79d0"

    UUID:
      description: UUID
      type: string
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      minLength: 36
      maxLength: 36
      example: "d0d654e6-97da-4848-b568-99fedccb642b"

    # ------------------------------------------------------
    # Complex types
    # ------------------------------------------------------
    Client:
      description: Client data
      type: object
      additionalProperties: false
      properties:
        serviceProviderId:
          $ref: '#/components/schemas/ServiceProviderId'
        channel:
          $ref: '#/components/schemas/Channel'
        terminalHandlerId:
          $ref: '#/components/schemas/TerminalHandlerId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        terminalUuid:
          $ref: '#/components/schemas/TerminalUuid'
      required:
        - serviceProviderId
        - channel
        - terminalHandlerId
        - terminalId
        - terminalUuid
      example:
        serviceProviderId: "AGID_01"
        channel: "POS"
        terminalHandlerId: "45856"
        terminalId: "34523860"
        terminalUuid: "c7a1b24b0583477292ebdbaa"

    Debt:
      description: Debt position
      type: object
      additionalProperties: false
      properties:
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
        amount:
          $ref: '#/components/schemas/EuroCents'
        description:
          $ref: '#/components/schemas/Description'
        dueDate:
          $ref: '#/components/schemas/DueDate'
    
    DebtPosition:
      description: Debt position
      type: object
      additionalProperties: false
      properties:
        debtPosition:
          type: array
          minItems: 0
          maxItems: 64
          items:
            $ref: '#/components/schemas/Debt'
    Error:
      description: Error details
      type: object
      additionalProperties: false
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        errorDescription:
          $ref: '#/components/schemas/ErrorDescription'
      required:
        - errorCode
        - errorDescription
      example:
        errorCode: "001000001"
        errorDescription: "Generic error"

    Errors:
      description: List of errors
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 32
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
      example:
        errors:
          - errorCode: "00000000A"
            errorDescription: "Generic error"
          - errorCode: "001000001"
            errorDescription: "Unexpected error from server"

    Metadata:
      description: Metadata for use and consumption of payee which issued the notice
      type: object
      aditionalProperties: false
      properties:
        key:
          $ref: '#/components/schemas/MetadataKey'
        value:
          $ref: '#/components/schemas/MetadataValue'
      required:
        - key
        - value
      example:
        key: "INT_REF"
        value: "123.456.00"

    MetadataList:
      description: List of metadata
      type: array
      minItems: 1
      maxItems: 15
      items:
        $ref: '#/components/schemas/Metadata'
      example:
        - key: "INT_REF"
          value: "123.456.00"
        - key: "REGIONAL_REF"
          value: "q76_089"

    Notice:
      description: Notice details
      type: object
      additionalProperties: false
      properties:
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        description:
          $ref: '#/components/schemas/Description'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
        payeeName:
          $ref: '#/components/schemas/PayeeName'
        officeName:
          $ref: '#/components/schemas/OfficeName'
        creditorReferenceId:
          $ref: '#/components/schemas/CreditorReferenceId'
        amount:
          $ref: '#/components/schemas/EuroCents'
        transfers:
          $ref: '#/components/schemas/Transfers'
        metadata:
          $ref: '#/components/schemas/MetadataList'
      required:
        - paymentToken
        - description
        - payeeCode
        - noticeNumber
        - payeeName
        - creditorReferenceId
        - amount
        - transfers
      example:
        paymentToken: "648fhg36s95jfg7DS"
        description: "Health ticket for chest x-ray"
        payeeCode: "06534340721"
        noticeNumber: "248394875506035295"
        payeeName: "ASL Roma"
        creditorReferenceId: "48394875506035295"
        amount: 12345
        transfers:
          - id: 1
            amount: 12345
            payeeCode: "06534340721"
            remittanceInformation: "Health ticket for chest x-ray"

    Notices:
      description: List of notices
      type: array
      minItems: 1
      maxItems: 5
      items:
        $ref: '#/components/schemas/Notice'
      example:
        - paymentToken: "648fhg36s95jfg7DS"
          description: "Health ticket for chest x-ray"
          payeeCode: "06534340721"
          noticeNumber: "248394875506035295"
          payeeName: "ASL Roma"
          creditorReferenceId: "48394875506035295"
          amount: 12345
          transfers:
            - id: 1
              amount: 12345
              payeeCode: "06534340721"
              remittanceInformation: "Health ticket for chest x-ray"

    PageMetadata:
      description: Metadata of a page of data
      type: object
      additionalProperties: false
      properties:
        size:
          $ref: '#/components/schemas/PageSize'
        totalElements:
          description: Total number of items
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
          example: 200
        totalPages:
          $ref: '#/components/schemas/PageNumber'
      example:
        size: 20
        totalElements: 100
        totalPages: 5

    PageOfTransactions:
      description: Page of transactions
      allOf:
        - type: object
          additionalProperties: false
          properties:
            transactions:
              $ref: '#/components/schemas/Transactions'
          required:
            - transactions
        - type: object
          additionalProperties: false
          properties:
            page:
              $ref: '#/components/schemas/PageMetadata'
          required:
            - page
      example:
        transactions:
          - id: "4658fcb36e520a65b1be79d0"
            creationTimestamp: "2024-03-06T13:15:54Z"
            lastUpdateTimestamp: "2024-03-06T13:16:33Z"
            status: "CLOSED_OK"
            client:
              serviceProviderId: "AGID_01"
              channel: "POS"
              terminalHandlerId: "45856"
              terminalId: "34523860"
              terminalUuid: "c7a1b24b0583477292ebdbaa"
            pspId: "AGID_01"
            pspBrokerId: "97735020584"
            channelId: "97735020584_03"
            noticesTotalAmount: 12345
            payerFees: 50
            payerAmount: 12395
            notices:
              - paymentToken: "648fhg36s95jfg7DS"
                description: "Health ticket for chest x-ray"
                payeeCode: "06534340721"
                noticeNumber: "248394875506035295"
                payeeName: "ASL Roma"
                creditorReferenceId: "48394875506035295"
                amount: 12345
                transfers:
                  - id: 1
                    amount: 12345
                    payeeCode: "06534340721"
                    remittanceInformation: "Health ticket for chest x-ray"
        page:
          size: 1
          totalElements: 5
          totalPages: 5

    Transaction:
      description: Transaction details
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/TransactionId'
        creationTimestamp:
          $ref: '#/components/schemas/CreationTimestamp'
        lastUpdateTimestamp:
          $ref: '#/components/schemas/LastUpdateTimestamp'
        status:
          $ref: '#/components/schemas/Status'
        client:
          $ref: '#/components/schemas/Client'
        pspId:
          $ref: '#/components/schemas/PspId'
        pspBrokerId:
          $ref: '#/components/schemas/BrockerId'
        channelId:
          $ref: '#/components/schemas/ChannelId'
        noticesTotalAmount:
          description: Total notices amount
          $ref: '#/components/schemas/EuroCents'
        payerFees:
          description: Fee charged to the payer
          $ref: '#/components/schemas/EuroCents'
        payeeFees:
          description: Fee charged to the payee
          $ref: '#/components/schemas/EuroCents'
        payerAmount:
          description: Total notices amount + Fee charged to the payer
          $ref: '#/components/schemas/EuroCents'
        idBundle:
          $ref: '#/components/schemas/IdBundle'
        idCiBundle:
          $ref: '#/components/schemas/IdCiBundle'
        notices:
          $ref: '#/components/schemas/Notices'
        standin:
          $ref: '#/components/schemas/Standin'
      required:
        - id
        - creationTimestamp
        - lastUpdateTimestamp
        - status
        - client
        - pspId
        - pspBrokerId
        - channelId
        - noticesTotalAmount
        - payerFees
        - payerAmount
        - notices
      example:
        id: "4658fcb36e520a65b1be79d0"
        creationTimestamp: "2024-03-06T13:15:54Z"
        lastUpdateTimestamp: "2024-03-06T13:16:33Z"
        status: "CLOSED_OK"
        client:
          serviceProviderId: "AGID_01"
          channel: "POS"
          terminalHandlerId: "45856"
          terminalId: "34523860"
          terminalUuid: "c7a1b24b0583477292ebdbaa"
        pspId: "AGID_01"
        pspBrokerId: "97735020584"
        channelId: "97735020584_03"
        noticesTotalAmount: 12345
        payerFees: 50
        payerAmount: 12395
        notices:
          - paymentToken: "648fhg36s95jfg7DS"
            description: "Health ticket for chest x-ray"
            payeeCode: "06534340721"
            noticeNumber: "248394875506035295"
            payeeName: "ASL Roma"
            creditorReferenceId: "48394875506035295"
            amount: 12345
            transfers:
              - id: 1
                amount: 12345
                payeeCode: "06534340721"
                remittanceInformation: "Health ticket for chest x-ray"

    Transactions:
      description: List of transactions
      type: array
      minItems: 0
      maxItems: 128
      items:
        $ref: '#/components/schemas/Transaction'
      example:
        - id: "4658fcb36e520a65b1be79d0"
          creationTimestamp: "2024-03-06T13:15:54Z"
          lastUpdateTimestamp: "2024-03-06T13:16:33Z"
          status: "CLOSED_OK"
          client:
            serviceProviderId: "AGID_01"
            channel: "POS"
            terminalHandlerId: "45856"
            terminalId: "34523860"
            terminalUuid: "c7a1b24b0583477292ebdbaa"
          pspId: "AGID_01"
          pspBrokerId: "97735020584"
          channelId: "97735020584_03"
          noticesTotalAmount: 12345
          payerFees: 50
          payerAmount: 12395
          notices:
            - paymentToken: "648fhg36s95jfg7DS"
              description: "Health ticket for chest x-ray"
              payeeCode: "06534340721"
              noticeNumber: "248394875506035295"
              payeeName: "ASL Roma"
              creditorReferenceId: "48394875506035295"
              amount: 12345
              transfers:
                - id: 1
                  amount: 12345
                  payeeCode: "06534340721"
                  remittanceInformation: "Health ticket for chest x-ray"

    Transfer:
      description: Details of the amount transfer to payee
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
        amount:
          $ref: '#/components/schemas/EuroCents'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        payeeName:
          $ref: '#/components/schemas/PayeeName'
        iban:
          $ref: '#/components/schemas/Iban'
        remittanceInformation:
          $ref: '#/components/schemas/RemittanceInfo'
        metadata:
          $ref: '#/components/schemas/MetadataList'
      required:
        - id
        - amount
        - payeeCode
        - remittanceInformation
      example:
        id: 1
        amount: 12345
        payeeCode: 06534340721
        remittanceInformation: "Health ticket for chest x-ray"

    Transfers:
      description: List of transfers
      type: array
      minItems: 1
      maxItems: 5
      items:
        $ref: '#/components/schemas/Transfer'
      example:
        - id: 1
          amount: 12345
          payeeCode: 06534340721
          remittanceInformation: "Health ticket for chest x-ray"

  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    CreateTransactionFromPa:
      description: Request to create a transaction from Public Administration portal
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              terminalUUid:
                $ref: '#/components/schemas/TerminalUuid'
              noticeNumber:
                $ref: '#/components/schemas/NoticeNumber'
              amount:
                $ref: '#/components/schemas/EuroCents'
            required:
              - terminalUUid
              - noticeNumber
              - amount

    CreateTransactionFromPos:
      description: Request to create a transaction from POS
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              payeeCode:
                $ref: '#/components/schemas/PayeeCode'
              noticeNumber:
                $ref: '#/components/schemas/NoticeNumber'
              amount:
                $ref: '#/components/schemas/EuroCents'
              idempotencyKey:
                $ref: '#/components/schemas/IdemPotencyKey'
            required:
              - payeeCode
              - noticeNumber
              - amount
              - idempotencyKey
    

    
    # ------------------------------------------------------
    # For activateByQrCode and
    # activateByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    Activate:
      description: Request to activate payment notice
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              idempotencyKey:
                $ref: '#/components/schemas/IdempotencyKey'
              amount:
                $ref: '#/components/schemas/EuroCents'
            required:
              - idempotencyKey
              - amount
            example:
              idempotencyKey: "47583764545_Ahf479elk0"
              amount: 12345

    # ------------------------------------------------------
    # For preCloseOrAbort
    # ------------------------------------------------------
    PreCloseOrAbort:
      description: Request to pre-close or abort a transaction
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/PreClose'
              - $ref: '#/components/schemas/Abort'       
    
    # ------------------------------------------------------
    # For close
    # ------------------------------------------------------
    Close:
      description: Request to close a transaction
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/CloseOutcome'
              paymentMethod:
                $ref: '#/components/schemas/PaymentMethod'
              paymentTimestamp:
                description: Timestamp of e-money transaction
                type: string
                format: date-time
                maxLength: 19
              presetId:
                $ref: '#/components/schemas/UUID'
            required:
              - outcome
              - paymentMethod
              - paymentTimestamp
            example:
              outcome: "CLOSE"
              paymentMethod: "PAGOBANCOMAT"
              paymentTimestamp: "2022-11-12T08:53:55"

    # ------------------------------------------------------
    # For receivePaymentStatus
    # ------------------------------------------------------
    PaymentStatusByNodo:
      description: Payment status communicated by the Nodo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentStatusByNodo'

  # ========================================================
  # Parameters
  # ========================================================
  parameters:
    #
    # NEW PARAMETERS
    #
    RequestId:
      name: RequestId
      in: header
      description: Request ID that will be logged by service
      required: true
      schema:
        $ref: '#/components/schemas/UUID'

    Version:
      name: Version
      in: header
      description: Version of the required API
      required: false
      schema:
        type: string
        pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        maxLength: 64
        example: "1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay"

    AcquirerId:
      name: AcquirerId
      in: header
      description: Acquirer ID assigned by PagoPA
      required: true
      schema:
        $ref: '#/components/schemas/AcquirerId'

    Channel:
      name: Channel
      in: header
      description: Channel originating the request
      required: true
      schema:
        $ref: '#/components/schemas/Channel'

    MerchantId:
      name: MerchantId
      description: Merchant ID. Mandatory when Channel equals POS.
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/MerchantId'

    TerminalId:
      name: TerminalId
      in: header
      description: ID of the terminal originating the transaction. It must be unique per acquirer and channel.
      required: true
      schema:
        $ref: '#/components/schemas/TerminalId'

  # ========================================================
  # Responses
  # ========================================================
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    
    # ------------------------------------------------------
    # For getDebtPosition
    # ------------------------------------------------------
    DebtPosition:
      description: Retrieved debt position
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DebtPosition' 

    # ------------------------------------------------------
    # For verifyByQrCode and verifyByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    VerifyProcessed:
      description: Verify processed
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/VerifyOk'
              - $ref: '#/components/schemas/VerifyOrActivateKo'

    # ------------------------------------------------------
    # For activateByQrCode and
    # activateByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    ActivateProcessed:
      description: Activate processed
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ActivateOk'
              - $ref: '#/components/schemas/VerifyOrActivateKo'

    # ------------------------------------------------------
    # For preCloseOrAbort
    # ------------------------------------------------------
    PreCloseOrAbortProcessed:
      description: Response to pre-close or abort successfully processed
      headers:
        Location:
          description: URL to get the status of the transaction (only for pre-close operation)
          required: false
          schema:
            $ref: '#/components/schemas/URI'
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/OkOutcome'
            required:
              - outcome
            example:
              outcome: "OK"
    
    # ------------------------------------------------------
    # For close
    # ------------------------------------------------------
    CloseProcessed:
      description: Response to close successfully processed
      headers:
        Location:
          description: URL to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: '#/components/schemas/URI'
        Retry-After:
          description: Number of seconds after which to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: '#/components/schemas/PositiveInteger'
        Max-Retries:
          description: Max number of retries to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: '#/components/schemas/PositiveInteger'
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/AllOrNothingOutcome'
            required:
              - outcome
            example:
              outcome: "OK"

    # ------------------------------------------------------
    # For getPaymentStatus
    # ------------------------------------------------------
    PaymentStatus:
      description: Payment status received
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentStatus'

    # ------------------------------------------------------
    # For receivePaymentStatus
    # ------------------------------------------------------
    PaymentStatusReceived:
      description: Payment status received
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/OkOutcome'
            required:
              - outcome
            example:
              outcome: "OK"

    TransactionNotFound:
      description: Transaction not found
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/TrxNotFoundOutcome'
            required:
              - outcome
            example:
              outcome: "PAYMENT_NOT_FOUND"

    # ------------------------------------------------------
    # For getLastTransactions
    # ------------------------------------------------------
    Transactions:
      description: Details of transactions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transactions'

  # ========================================================
  # Security schemes
  # ========================================================
  securitySchemes:
    bearerAuth:
      description: A bearer token in the format of a JWS and conforms to the specifications included in RFC8725
      type: http
      scheme: bearer
      bearerFormat: JWT